### ISSUE TITLE
1.3.3.3

### ISSUE THREAD

**Issue by IdrisDose** [Tygra/RPG#2]
Can I update this for 1.3.3.3 and run it on a server? Considering Geldar has shut down? If not it's okay :D Just miss the good ol' memories of this server.

**Comment by Tygra** [comment]
Sure. If you need help just post an issue, I need the practice:P If you are considering running a server and need help just drop me a message. I'm happy to help with stuff like this or web-moderating, just not with ingame moderation:P

**Comment by Tygra** [comment]
edit: woops missed the whole point of my reply at first
